export type Movie = {
  title: string,
  posterUrl: string,
  backgroundUrl: string,
  backgroundColor: string,
  previewUrl: string,
  previewImage: string,
  genre: string,
  release: number,
  director: string,
  starring: string[],
  time: string,
  rating: number,
  votes: number,
  description: string,
  id: number,
  isFavorite: boolean,
  videoUrl: string,
};
